# Generated by Django 5.1.7 on 2025-03-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_category_name_en_category_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='item',
            name='color_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='items/img_box', verbose_name='Главная картинка товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='items/img_box', verbose_name='Главная картинка товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_available_en',
            field=models.BooleanField(default=False, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_available_ru',
            field=models.BooleanField(default=False, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='item',
            name='model_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='item',
            name='model_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='item',
            name='price_en',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='item',
            name='price_ru',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='item',
            name='production_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Производство'),
        ),
        migrations.AddField(
            model_name='item',
            name='production_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Производство'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок товара'),
        ),
    ]
