# Generated by Django 5.1.7 on 2025-03-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tovar', verbose_name='Главная картинка товара'),
        ),
    ]
