# Generated by Django 5.1.7 on 2025-03-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_remove_item_user_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/img_box', verbose_name='Главная картинка товара'),
        ),
    ]
