# Generated by Django 5.1.7 on 2025-03-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адресс')),
                ('schedule', models.TextField(verbose_name='График')),
                ('phones', models.TextField(verbose_name='Телефоны')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
            ],
        ),
    ]
